### ISSUE TITLE
Meeting 4, Whole Group Meeting- Gennadii Teaching Us.

### ISSUE THREAD

**Issue by misik-eng** [MIT-Emerging-Talent/ET6-foundations-group-05#8]
This time hopefully we won't have meeting time restriction, I forgot  that I have a premium account last time haha. sorry:(

Group Meeting 4 The Shining Stars
Wednesday, December 25 · 2:00 – 3:30pm
Time zone: EST
Google Meet joining info
Video call link: https://meet.google.com/bjy-yesb-krk

- [x] Gennadii will create a branch for our Learning Goals and demonstrate how to create a branch, make a commit, and push it to the learning branch.

- [x] Afterward, one of us can create another branch for our Constraints and follow the same process for the Constraints.(To practice)

- [x] Next, we need to discuss our project board-- when and how we should use it. One of us will read this [article](https://github.com/MIT-Emerging-Talent/ET6-foundations-group-05/blob/main/collaboration/guide/5_project_board.md) and explain it to the group.

- [x] Finally, we can begin the development phase. This means finding two challenges from any source (Gennadii suggested LeetCode yesterday—thank you again, Gennadii!) and creating a branch, for example, challenge_number1, to start working on our personal challenges.

You can find explanations for our development step [here](https://github.com/MIT-Emerging-Talent/ET6-foundations-group-05/blob/main/collaboration/guide/6_development.md)

**Comment by imwaymaran** [comment]
We had our fourth meeting on Wednesday, December 25. I showed the team how to create a branch, make commits, and push changes, and we practiced this with the Learning Goals document. We also talked about how to use our project board. Finally, we started the development phase by choosing challenges to work on individually. Closing this issue now.
